# consts.py
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

FLAG_ROWS = 3
FLAG_COLS = 4

# game_field.py
flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

WHITE = (255, 255, 255)
RED = (255, 0, 0)
# GREEN = (0, 255, 0)
GREEN =(119, 154, 32)
BLACK = (0, 0, 0)


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 25
